### ISSUE TITLE
Cant seem to find the corect syntax for changin one element in a list.

### ISSUE THREAD

**Issue by HansOMartinsen** [IngoGege/xXMLConfigFile#11]
With the following XML. How would you write the config to change 
`<string id="HeadingRDWA">Password Reset Portal2</string>
`to
`<string id="HeadingRDWA">SomethingElse</string>`
```
<?xml version="1.0"?>
<rdwastr:strings xmlns:rdwastr="urn:microsoft.com:rdwastrings">
  <string id="PageTitle">Password Reset Portal</string>
  <string id="NoScriptWarning">
    <p id="NoScript1">RD Web Access requires JScript. This Web browser either does not support JScript, or scripts are being blocked.</p>
    <br />
    <br />
    <p id="NoScript2">To find out whether your browser supports JScript, or to allow scripts, see the browser's online Help.</p>
  </string>
  <string id="HeadingRDWA">Password Reset Portal2</string>
  <string id="HeadingApplicationName">Password Reset Portal</string>
  <string id="Help">Help</string>
  <string id="SignOut">Sign out</string>
  <string id="SearchingForApps">Searching for available RemoteApp programs...Ãƒâ€šÃ‚Â </string>
  <string id="CurrentFolder">Current folder: </string>
  <string id="ParentFolder">Up</string>
  <string id="OptimizeMyExperience">Optimize my experience for a LAN network when connecting to the computer or application.</string>
  <string id="PrivateComputer">I am using a private computer that complies with my organization's security policy.</string>
  <string id="MoreInformation">More information...</string>
  <string id="PrivateMore">By selecting this option you can save your credentials so that they can be used in the future when connecting to these programs. Before you select this option, please ensure that saving your credentials is in compliance with your organization's security policy.</string>
  <string id="HideMore">Hide additional information...</string>
  <string id="PrivacyLink">Privacy</string>
</rdwastr:strings>
```

**Comment by HansOMartinsen** [comment]
It seems you are enforcing namespace prefix to all sublevels. THat is not in use in the file I am trying to edit, and so it will never work. 

I suggest refactoring the way you handle XPaths, or adding new logic to handle only partial enforcement of namespace prefix, or even a method to remove the prefix altogether.

**Comment by IngoGege** [comment]
Hi @HansOMartinsen ,
just started looking into this. You can define XMLNS in the resource. I'm enforcing to retrieve the XMLNS, if nothing was provided. This is due to the fact that SelectSingleNode needs one, otherwise elemts won't be found.
Ciao,
Ingo

**Comment by IngoGege** [comment]
Hi @HansOMartinsen ,
found it. My bad as I misread something. You're correct that I'm enforcing XMLNamespacemanager. With this it's not possible to search for attributes without Namespaces. I'll fix that soon.
Thanks for highlighting and patience!
Ciao,
Ingo

**Comment by IngoGege** [comment]
Hi @HansOMartinsen ,
issue is fixed in version 2.0.0.2. Your config should looks like this:
XMLConfigFile
{
        ConfigPath = 'C:\temp\your.config'
        XPath      = '//string[@id='HeadingRDWA']'
        Name       = $null
        Value      = 'SomethingElse'
        isElementTextValue = $true
        Ensure = 'present'
        EnforceNullXMLNS    = $true
}

Please let me know if this works for you, so I can close this issue.
Ciao,
Ingo

**Comment by HansOMartinsen** [comment]
There are no 2.0.0.2 version  available on the Powershell Gallery.
So I downloaded the master repo. That gave me the following error when trying to run the config.

The command Get-TargetResource of the PS resource xXMLConfigFile does not implement the key property Name mentioned in the corresponding MOF schema file C:\Program Files\WindowsPowerShell\Modules\xXMLConfigFile\DscResources\xXMLConfigFile\xXMLConfigFile.schema.mof as a mandatory parameter. All key parameters mentioned in the schema file must be implemented by the command Get-TargetResource as mandatory function parameters.

I have not done much research on why this is, I am afraid.
Maybe you know off hand.

**Comment by IngoGege** [comment]
Hi

**Comment by IngoGege** [comment]
Successful tested with new machine and therefore closing the issue.
