### ISSUE TITLE
Unable to delete multiple elements at once

### ISSUE THREAD

**Issue by micxba** [IngoGege/xXMLConfigFile#14]
Having a little dilemma - XML Snippet as follows:

&lt;configuration&gt;    
  &lt;my.config&gt;      
     &lt;portal&gt;         
            &lt;schemeAdmin loopback="false"&gt;           
                &lt;allow&gt;0.0.0.0/0.0.0.0&lt;/allow&gt;           
                &lt;allow&gt;1.2.2.2&lt;/allow&gt;        
           &lt;/schemeAdmin&gt;        
           &lt;portalAdmin loopback="false"&gt;          
               &lt;allow&gt;0.0.0.0/0.0.0.0&lt;/allow&gt;          
               &lt;allow&gt;1.2.2.2&lt;/allow&gt;        
          &lt;/portalAdmin&gt;        
          &lt;editMode loopback="false"&gt;          
               &lt;allow&gt;0.0.0.0/0.0.0.0&lt;/allow&gt;        
          &lt;/editMode&gt;
....

And a DSC Configurations Snippet as such:

XMLConfigFile editModeAllowListOff {
      ConfigPath = "...\web.config"        
      XPath      = '//configuration/my.config/portal/*'        
      Name       = 'allow'        
      isElementTextValue = $true        
      Ensure     = 'Absent' 
}

It sort of works however when I apply the configuration it only removes one allow element - subsequent runs again remove one more until they are gone. Since it is undetermined how many there are - is there a more elegant way to remove ALL <allow> elements?

**Comment by IngoGege** [comment]
@micxba this is by design as the resources is built on SelectSingleNode, which always picks the first node, which was found.
Ciao,
Ingo
