### ISSUE TITLE
Adding key value pairs in a for-loop

### ISSUE THREAD

**Issue by qa7720** [IngoGege/xXMLConfigFile#16]
Hello XMLConfigFile-Team,

I had an issue adding appSetting key value pairs in a for-loop. 
I fixed it by adding following function to .\xxmlconfigfile\Misc\xXMLConfigFileCommonFunctions.psm1

`function FixXPath() {`
`  # When creating keys in a loop a unique combination of $ConfigPath and $XPath is required,`
`  # otherwise it will result in following exception:`
`  #   The key properties combination 'app.config:://appSettings/add' is duplicated for keys `
`  #   'ConfigPath,XPath' of resource 'XMLConfigFile' in node 'node-name'. Please make sure `
`  #   key properties are unique for each resource in a node.`
`  #`
`  # to achieve this the key name is added to the xpath parameter in the setup:`
`  #`
`  #   foreach ($key in $keys) {`
`  #     XMLConfigFile "app:$($key.name)"`
`  #     {`
`  #       ...`
`  #       XPath = "//appSettings/add[@key='$($key.name)']"`
`  #       ...`
`  #     }`
`  #   }`
`  #`
`  # But when the node is selected with `
`  #   $root.SelectSingleNode("$XPath[@$Attribute1='$Name']")`
`  # it will result in following exception:`
`  #   Exception calling "CreateElement" with "2" argument(s): "The '[' character, `
`  #   hexadecimal value 0x5B, cannot be included in a name."`
`  # since the XPath looks like this:`
`  #   //appSettings/add[@key='myKey'][@key='myKey']`
`  # To prevent this we remove the unique part:`
`  [CmdletBinding()]`
`  [OutputType([string])]`
`  param`
`  (`
`    [string]$XPath`
`  )`
`  if($XPath.IndexOf("[") -gt 0) {`
`    return $XPath.Substring("", $XPath.IndexOf("["))`
`  }`
`  else {`
`    return $XPath`
`  }`
`}`

and invoke it every method after the replace call on the XPath variable

`#add XMLNameSpaceManager to XPath`
`$XPath = $XPath -replace "/(?!/)", "/$($NSPrefix):"`
`$XPath = FixXPath $XPath`

Maybe you can take a look at it and if it's OK integrate it.
[xXMLConfigFileCommonFunctions.psm1.txt](https://github.com/IngoGege/xXMLConfigFile/files/3140840/xXMLConfigFileCommonFunctions.psm1.txt)

**Comment by IngoGege** [comment]
@qa7720 thanks for this. Looks promising. I'll have a look.
Cioa,
Ingo

**Comment by IngoGege** [comment]
@qa7720 do you think my commit https://github.com/IngoGege/xXMLConfigFile/commit/d6ef0ff6afb6eed37929226fc3d2f24fca267218 addressed your issue?
Thanks in advance!

**Comment by qa7720** [comment]
@IngoGege I think it should.
We migrated the target project to .NET core and moved to use .json config files.
Therefore I am unable to test it.
